<a class="b-asideLogo" href="/"></a>
<nav class="b-asideNav">
    <a class="b-asideNav-item " href="/about">About</a>
    <a class="b-asideNav-item " href="/campaign">Campaign</a>
    <a class="b-asideNav-item " href="/lookbook">Lookbook</a>
    <a class="b-asideNav-item " href="/news">News</a>
    <a class="b-asideNav-item " href="/private-order">Private order</a>
    <a class="b-asideNav-item " href="/contacts">Contacts</a>
</nav>